apiVersion: batch/v1
kind: Job
metadata:
  name: curl-job-nodeport
  namespace: servers
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: nginx-curl
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - curl http://10.132.0.3:30036
