apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: {{ .Release.Name }}-service-port
    protocol: {{ .Values.protocol }}
    port: {{ .Values.port }}
    targetPort: {{ .Release.Name }}-http
